### ISSUE TITLE
Slack access?

### ISSUE THREAD

**Issue by johnsanders** [CasparCG/help#10]
Hello... sorry if this isn't the place for this, but I'm a producer at CNN in London and we're looking at possibly using CasparCG for a new project.  I've been playing with the software and working on a custom controller for our exact use case and have been absolutely blown away at what it's capable of.

Ryan McKenna at BBC Scotland suggested I join the Slack channel, but it seems to be locked down to a few email domains.

Is there any way I might join with an @cnn.com address?

Thanks!!  And thanks for all the work you've done on this project so far.  It is really amazing.

**Comment by baltedewit** [comment]
I think @hummelstrand can make that happen.

**Comment by johnsanders** [comment]
awesome... it's john.sanders@cnn.com

thank you!!

**Comment by john-sanders** [comment]
@5opr4ni I see this is closed as solved, but I'm still not able to sign up at casparcg.slack.com.  Am I missing something?

**Comment by dotarmin** [comment]
@johnsanders I have sent you a new invitation. 

Best regards.

**Comment by johnsanders** [comment]
got it.. thank you.  Was spam filtered.
