### ISSUE TITLE
autoplay greyed out

### ISSUE THREAD

**Issue by samdisk11** [CasparCG/help#11]
i am unable to use the autoplay feature because it is greyed out. anyone know how to enable it? 
![image](https://user-images.githubusercontent.com/24478471/44294999-21122000-a266-11e8-9399-09dbc4516213.png)

**Comment by dotarmin** [comment]
Hi @samdisk11 

If you put your clip into a group and enable the `Auto play`on the group it-self then it will be available for all clips within the group.

Best regards,
Armin
