### ISSUE TITLE
Template Generator not installing on Adobe Animate CC

### ISSUE THREAD

**Issue by beterthanlife** [CasparCG/help#12]
When trying to install Template Generator 2.1.2 on Adobe Animate CC 2018, the extension manager says that the extension has installed fine but it doesnt appear in the list of installed extensions and the "casper" option wont show in the main-menu Window drop-down.

**Comment by dotarmin** [comment]
Hi!

Unfortunately, this is a known issue for the moment. The community is working on a solution and as soon as it's solved I can ping you and redirect you to appropriate page containing this information.

Best regards,
Armin

**Comment by silid** [comment]
The extension has probably installed to the wrong locale.
Have a look in `%LOCALAPPDATA%\Adobe\Animate CC 2018\` and see how many locales are listed.

You will probably have en_US and one other. The plugin has installed in the other one.
Copy all the files from the other locale to the en_US one and it will probably work.

**Comment by beterthanlife** [comment]
That works. Thanks silid!
