### ISSUE TITLE
Caspar CG Atem Control

### ISSUE THREAD

**Issue by rossmase** [CasparCG/help#17]
Hi all,

We've been researching more and more into Caspar CG. Such a great program.

Not sure if this is the place to share this, but we're after some help!

We're having some issues with regards to integrating Caspar CG with our ATEM Switchers and using some of the advertised functionality. We have both a 2ME and 1ME 4K.

Is there any information or tips on how to get this working? We're most keenly interested in Auto-roll but also just in general how we can link these two systems together. 

Thanks in advance!

**Comment by silid** [comment]
Hi @rossmase  - welcome to the community.
I'm not sure exactly what information you want.

You can find some information on Atem config here:
https://github.com/CasparCG/help/wiki/Server:-Vision-Mixer-Settings#blackmagic-design-atem-configuration

Also don't forget to look at the community forum:
https://casparcgforum.org/

**Comment by Julusian** [comment]
The standard client can send commands to the ATEM but I don't think it can receive commands from the ATEM and act on them.

You will to use Just Macros or write your own client to achieve this

**Comment by rossmase** [comment]
Thanks Julian, understood. We'll look into Just Macros integration with
this.

Much appreciated.
------------------------------

Ross Mason

ross.mason@fluxbroadcast.com <ed.mellish@fluxbroadcast.com>

M: 0590917800   |   D: 02035156957

Unit 10, 2 - 4 Ropley Street,
<https://maps.google.com/?q=2+-+4+Ropley+Street,+London,+E2+7SW,+United+Kingdom&entry=gmail&source=g>
London, E2 7SW, United Kingdom
<https://maps.google.com/?q=2+-+4+Ropley+Street,+London,+E2+7SW,+United+Kingdom&entry=gmail&source=g>


Registered in England & Wales no. 09170408, 12 Blackstone Close,
Farnborough, Hampshire, GU14 9JW
<https://maps.google.com/?q=12+Blackstone+Close,+Farnborough,+Hampshire,+GU14+9JW&entry=gmail&source=g>
.
