### ISSUE TITLE
What does CINF returns?

### ISSUE THREAD

**Issue by luckcfm** [CasparCG/help#19]
When I run: CINF AMB for instance, I get: 
#200 CINF OK
"AMB" MOVIE 6445960 20170413102935 268 1/25

What are those numbers? Total frames? Length? Timestamp?

**Comment by Julusian** [comment]
Filename
Type (STILL/MOVIE/AUDIO)
Filesize (Bytes)
Last Modified
Frame count
Frame rate/duration

**Comment by luckcfm** [comment]
Thank you @Julusian I couldn't find it at the docs. I`ll close this for now.

**Comment by silid** [comment]
I have now added @Julusian comment to the AMCP wiki docs for future reference.

https://github.com/CasparCG/help/wiki/AMCP-Protocol#cinf
