### ISSUE TITLE
CasparCG + NDI on Linux - Incorrect file extentsion

### ISSUE THREAD

**Issue by robertpotts-AGB** [CasparCG/help#41]
When initally setting up CasparCG on Linux (using the Docker Install) with NDI the CasparCG window told me it could not load the libndi.so.3 file despite me copying the lib files over from the latest newTek NDI SDK. 

When using the latest NDI pack from NewTek the file names are:
libndi.so
libndi.so.4
libndi.so.4.5.3

Having re-named one of the files to libndi.so.3 it works and NDI works as expected. Can an update to Caspar make it look for just libndi.so ? rather than a version number? 

Also can some brief instructions be provided on getting NDI working on linux for general use? Happy to help provide if required

**Comment by baltedewit** [comment]
These would be the place for any additional instructions on using NDI with server 2.3:

https://github.com/CasparCG/help/wiki/NDI-Producer
https://github.com/CasparCG/help/wiki/NDI-Consumer

The original PR reads that "v3.7 and later" is required, I'm going to assume that means it was never intended to be ran with v4. https://github.com/CasparCG/server/pull/1112 The file extension therefore is in fact correct. Nonetheless good to know that v4 works in your experience.

**Comment by Julusian** [comment]
The next 2.3 build/release will try using libndi.so.4 instead now. https://github.com/CasparCG/server/commit/1d230e2a12a232f894291f6c9618cf1bf2b3f533
I havent tried, but I think this will now simply require v4.0+ (current is v4.5.1), and would likely work with even older via the same rename trick.
I did consider dropping the .4 file extension requirement, but that is something defined by the ndi sdk and so I dont know if that could have any negative effects so this feels safer.

**Comment by robertpotts-AGB** [comment]
Thanks for the update,
