### ISSUE TITLE
Link is 404 for sample configs in guide page “ Guide: Example Server Configuration”

### ISSUE THREAD

**Issue by stemcc** [CasparCG/help#45]
I’m receiving “file not found or has been removed” errors when trying to access the example config files in the guide page “ Guide: Example Server Configuration”

**Comment by silid** [comment]
@vimlesh1975 I think this was your drive folder - can you take a look?

**Comment by vimlesh1975** [comment]
I have update the link. Thanks for reporting.

**Comment by silid** [comment]
Thanks @vimlesh1975
