### ISSUE TITLE
HTML Performance Issue

### ISSUE THREAD

**Issue by IPxK** [CasparCG/help#6]
Hi,

I was wondering if anyone notice a performance issue when using a HTML link in CasparCG. I notice after about an hour of using a link, the RAM consumption and using the CasparCG diagnostic tool will jump to an alarming rate.

**Comment by dotarmin** [comment]
Hi,

I haven't tested this myself but maybe someone else has?

ping @julusian

**Comment by IPxK** [comment]
I'm using version 2.2.0.4 Beta 1. I had to use this one because it allowed the mapped feature in Chromium

**Comment by dotarmin** [comment]
@IPxK Could you please provide more information about the hardware and the command(s) you send.

**Comment by baltedewit** [comment]
Okay, and are you using the system audio producer as well? That is known to have a memory leak in 2.2, currently.

**Comment by dotarmin** [comment]
> Okay, and are you using the system audio producer as well? That is known to have a memory leak in 2.2, currently.

As @baltedewit is writing, a known bug exists if <system-audio/> is used. [Server/#946](https://github.com/CasparCG/server/issues/946)

Thanks @baltedewit! :)

**Comment by dotarmin** [comment]
@IPxK can you try to remove system audio from your config (if you use it) and test your HTML link again?

**Comment by IPxK** [comment]
Hi,

My computer specs are:

Windows 10 x64 Bit Pro
Intel Xeon E3-1535M v5 @ 2.90 GHz
16GB RAM
240GB SSD
Quadro M5000M (Driver 391.58)
BlackMagic Decklink Quad 2

The website I'm testing is our custom website:
https://app.singular.live/appinstances/16209/outputs/Output/onair?aspect=16:9

I also tried yahoo.com and cnn.com which has the same issue.

I don't have system audio enable, here is my config.
So far I'm only testing with 1 output on my decklink card

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <paths>
    <media-path>media/</media-path>
    <log-path>log/</log-path>
    <data-path>data/</data-path>
    <template-path>template/</template-path>
    <font-path>font/</font-path>
  </paths>
  <lock-clear-phrase>secret</lock-clear-phrase>
  <channels>

 <channel>
        <video-mode>1080i5994</video-mode>
        <consumers>
            <decklink>
                <device>1</device>
                <key-device>device + 1</key-device>
                <embedded-audio>true</embedded-audio>
                <latency>default</latency>
                <keyer>external</keyer>
                <key-only>false</key-only>
                <buffer-depth>4</buffer-depth>
            </decklink>
        </consumers>
    </channel>
  </channels>
  <controllers>
    <tcp>
      <port>5250</port>
      <protocol>AMCP</protocol>
    </tcp>
  </controllers>
  <amcp>
    <media-server>
      <host>localhost</host>
      <port>8000</port>
    </media-server>
  </amcp>
</configuration>

**Comment by dotarmin** [comment]
@IPxK Thanks for the additional information. 

@Julusian, have you experienced something similar to this when you played around with HTML? Thanks in advance.

**Comment by Julusian** [comment]
I may have seen this happen. I'll try and run some tests next week to see.

**Comment by IPxK** [comment]
Here some screenshots from the CasparCG Diagnostic tool if you need it.
I took one when I started the test, then an hour later and then an hour & 15 minutes.

![beginnng](https://user-images.githubusercontent.com/39736498/40801752-8fe9973c-64c8-11e8-8ff6-a4426be44543.PNG)

![2nd hour](https://user-images.githubusercontent.com/39736498/40801760-93a6b7b0-64c8-11e8-9a47-51b1ca8303d1.PNG)


![2nd hour and 15 min](https://user-images.githubusercontent.com/39736498/40801766-95f3a0b4-64c8-11e8-9754-e3ebf45a0dcf.PNG)

**Comment by dotarmin** [comment]
> @Julusian: I'll try and run some tests next week to see.

Thanks Julian! 🙇

**Comment by IPxK** [comment]
Did you find anything on your test @Julusian ?

**Comment by Julusian** [comment]
I was away for all of last week, but am having a look currently.

Interestingly the graph doesn't go back to normal after removing the html producer. Only after removing the decklink.
I am still trying things (eg other producers, framerates), but at over an hour per test it is slow progress

**Comment by IPxK** [comment]
Okay great thank you for taking a look at this!

**Comment by Julusian** [comment]
74 minutes later and I have the exact same thing. This time with only amb on loop, so it appears to be not producer specific.
![help6-2](https://user-images.githubusercontent.com/1327476/40944260-06e7f064-684c-11e8-869c-83b4cfa4676e.PNG)

I left the same test running in 1080i5000 overnight, and it is performing normally so it looks to be an issue with the decklink sync when running in 1080i5994

**Comment by baltedewit** [comment]
I think now might be a good time to open an issue in the [CasparCG/Server](https://github.com/CasparCG/Server) repository.

**Comment by dotarmin** [comment]
> I think now might be a good time to open an issue in the CasparCG/Server repository.

ping @IPxK 

Thanks all for the help! :)

**Comment by IPxK** [comment]
Okay thank you for all your help everyone.

I just open an issue in the CasparCG/Server repository.

**Comment by Julusian** [comment]
https://github.com/CasparCG/server/issues/1015
