### ISSUE TITLE
media-scanner /cls returns nothing

### ISSUE THREAD

**Issue by magnonellie** [CasparCG/help#8]
I'm trying to run the 2.2 beta on Ubuntu 18.04. I compiled CasparCG server through the docker scripts and it seems to work just fine. Having to also compile the media-scanner kind of tripped me up, but it seems to be somewhat working right now anyway. The problem I'm having is that while I can see all my templates perfectly fine, media-scanner doesn't actually seem to return anything on the `/cls` endpoint which means nothing shows up for CasparCG. Running the little snippet present in the readme of the media-scanner project shows that it does pick up on removals and additions, so I don't think that's the problem. It's just that it doesn't forward the information in the database to the `/cls` endpoint. Am I doing something wrong or is this a bug?

I don't know if it's useful, but this is what is returned running `curl localhost:8000/cls`:
```
200 CLS OK

```

Thank you!

**Comment by magnonellie** [comment]
Well, I managed to solve my problem. After I deleted all data pertaining to media-scanner, I noticed some errors about ffmpeg and realized I hadn't installed that on my computer yet. :sweat_smile:

**Comment by akr4m** [comment]
Replace the scanner file to old scanner file inside server folder.
I think that will help you.
